# Generated by Django 5.0.6 on 2024-05-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
        ('sbook', '0007_course_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='QuizzUser',
        ),
    ]
