# Generated by Django 5.0.6 on 2024-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_quizz_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='profile',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
