# Generated by Django 5.0.6 on 2024-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0004_alter_quizz_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizz",
            name="description",
            field=models.CharField(default="no description", max_length=1023),
            preserve_default=False,
        ),
    ]
