# Generated by Django 5.0.6 on 2024-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0005_quizz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizz",
            name="description",
            field=models.TextField(),
        ),
    ]
