# Generated by Django 5.0.6 on 2024-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_rename_quizzanswerattempt_quizzattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzattempt',
            name='remark',
            field=models.JSONField(default=None, null=True),
        ),
    ]
