# Generated by Django 5.0.6 on 2024-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_alter_quizzattempt_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzattempt',
            name='mark',
            field=models.SmallIntegerField(default=40),
            preserve_default=False,
        ),
    ]
