# Generated by Django 5.0.6 on 2024-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0013_remove_quizzattempt_mark_quizzattempt_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizz",
            name="stars",
            field=models.IntegerField(default=0),
        ),
    ]
