# Generated by Django 5.0.6 on 2024-06-11 13:01

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0014_quizz_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizz",
            name="description",
            field=martor.models.MartorField(),
        ),
    ]
