# Generated by Django 5.0.6 on 2024-06-11 14:21

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0015_alter_quizz_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizz",
            name="description",
            field=mdeditor.fields.MDTextField(),
        ),
    ]
