# Generated by Django 5.0.6 on 2024-06-11 18:08

import mdeditor.fields
import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0016_alter_quizz_description"),
        ("sbook", "0014_remove_serie_levels_course_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizz",
            old_name="data",
            new_name="questions",
        ),
        migrations.RemoveField(
            model_name="quizzattempt",
            name="remark",
        ),
        migrations.AddField(
            model_name="quizz",
            name="epilog",
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name="quizz",
            name="instructions",
            field=mdeditor.fields.MDTextField(default="nothing here..."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizz",
            name="prolog",
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name="quizz",
            name="series",
            field=models.ManyToManyField(related_name="quizzes", to="sbook.serie"),
        ),
        migrations.AddField(
            model_name="quizz",
            name="views",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizzattempt",
            name="remarks",
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name="quizzuser",
            name="starred_quizzes",
            field=models.ManyToManyField(related_name="starred_by", to="quizz.quizz"),
        ),
        migrations.AlterField(
            model_name="quizz",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
    ]
