# Generated by Django 5.0.6 on 2024-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0018_remove_quizz_classrooms"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizz",
            name="classrooms",
            field=models.ManyToManyField(related_name="quizzes", to="school.classroom"),
        ),
    ]
