# Generated by Django 5.0.6 on 2024-06-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0019_quizz_classrooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizz",
            name="series",
        ),
    ]
