# Generated by Django 5.0.6 on 2024-05-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0003_level_user_bio_user_profile_course_serie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
    ]
