# Generated by Django 5.0.6 on 2024-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0005_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="serie",
            name="name",
            field=models.CharField(default="None", max_length=32),
            preserve_default=False,
        ),
    ]
