# Generated by Django 5.0.6 on 2024-05-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbook', '0006_serie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='series',
            field=models.ManyToManyField(related_name='courses', to='sbook.serie'),
        ),
    ]
