# Generated by Django 5.0.6 on 2024-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbook', '0008_alter_course_profile_alter_level_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(),
        ),
    ]
