# Generated by Django 5.0.6 on 2024-06-11 13:01

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0012_alter_course_levels_alter_course_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=martor.models.MartorField(),
        ),
    ]
