# Generated by Django 5.0.6 on 2024-06-11 18:08

import mdeditor.fields
import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0013_alter_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="levels",
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=mdeditor.fields.MDTextField(default="nothing here..."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="level",
            name="description",
            field=mdeditor.fields.MDTextField(default="nothing here..."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="level",
            name="series",
            field=models.ManyToManyField(related_name="levels", to="sbook.serie"),
        ),
        migrations.AddField(
            model_name="serie",
            name="description",
            field=mdeditor.fields.MDTextField(default="nothing here..."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="levels",
            field=models.ManyToManyField(related_name="courses", to="sbook.level"),
        ),
        migrations.AlterField(
            model_name="course",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="series",
            field=models.ManyToManyField(related_name="courses", to="sbook.serie"),
        ),
        migrations.AlterField(
            model_name="level",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
        migrations.AlterField(
            model_name="serie",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "profile",
                    models.ImageField(
                        default=profile_images.get_random_file,
                        upload_to="media/profiles",
                    ),
                ),
                ("description", mdeditor.fields.MDTextField()),
                (
                    "course",
                    models.ManyToManyField(related_name="topics", to="sbook.course"),
                ),
            ],
        ),
    ]
