# Generated by Django 5.0.6 on 2024-06-12 17:21

import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0015_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="profiles/courses"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="profiles/levels"
            ),
        ),
        migrations.AlterField(
            model_name="serie",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="profiles/series"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="profiles/topics"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="profiles/user"
            ),
        ),
    ]
