# Generated by Django 5.0.6 on 2024-06-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0016_alter_course_profile_alter_level_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="--------", max_length=32),
            preserve_default=False,
        ),
    ]
