# Generated by Django 5.0.6 on 2024-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0017_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
