# Generated by Django 5.0.6 on 2024-06-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0018_alter_user_username"),
        ("school", "0005_alter_classroom_code_of_conduct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("c:n", "note creation"),
                            ("m:n", "note editing"),
                            ("s:n", "note starring"),
                            ("d:n", "note deletion"),
                            ("vc:n", "note visibility change"),
                            ("c:q", "quizz creation"),
                            ("a:q", "quizz attempt"),
                            ("d:q", "quizz deletion"),
                            ("s:q", "quizz starring"),
                            ("c:c", "classroom creation"),
                            ("c:s", "school creation"),
                            ("msg", "message"),
                            ("c:a", "account creation"),
                            ("m:a", "account modification"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("params", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="school.userrole",
            ),
        ),
    ]
