# Generated by Django 5.0.6 on 2024-06-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0019_event_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("c:n", "note creation"),
                    ("m:n", "note editing"),
                    ("s:n", "note starring"),
                    ("d:n", "note deletion"),
                    ("vc:n", "note visibility change"),
                    ("c:q", "quizz creation"),
                    ("a:q", "quizz attempt"),
                    ("d:q", "quizz deletion"),
                    ("s:q", "quizz starring"),
                    ("c:c", "classroom creation"),
                    ("c:s", "school creation"),
                    ("msg", "message"),
                    ("c:a", "account creation"),
                    ("m:a", "account modification"),
                ],
                editable=False,
                max_length=8,
            ),
        ),
    ]
