# Generated by Django 5.0.6 on 2024-06-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0021_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Faq",
        ),
    ]
