# Generated by Django 5.0.6 on 2024-06-12 17:34

import mdeditor.fields
import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sbook", "0016_alter_course_profile_alter_level_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("code_of_conduct", mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ImageField(
                        default=profile_images.get_random_file,
                        upload_to="profiles/school",
                    ),
                ),
                ("description", mdeditor.fields.MDTextField()),
                ("name", models.CharField(max_length=64)),
                ("hidden", models.BooleanField()),
                ("code_of_conduct", mdeditor.fields.MDTextField()),
                (
                    "admins",
                    models.ManyToManyField(
                        related_name="admins_schools", to="sbook.user"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="teached_schools", to="sbook.user"
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="teaches_schools", to="sbook.user"
                    ),
                ),
            ],
        ),
    ]
