# Generated by Django 5.0.6 on 2024-06-12 20:24

import django.db.models.deletion
import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0016_alter_course_profile_alter_level_profile_and_more"),
        ("school", "0002_classroom_admins_classroom_courses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "profile",
                    models.ImageField(
                        default=profile_images.get_random,
                        upload_to="profiles/user-roles/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schoolAccount",
                        to="sbook.user",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_users",
                        to="school.userrole",
                    ),
                ),
            ],
        ),
    ]
