# Generated by Django 5.0.6 on 2024-06-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_userrole_schooluser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="members",
        ),
    ]
