# Generated by Django 5.0.6 on 2024-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sbook", "0019_event_user_role"),
        ("school", "0005_alter_classroom_code_of_conduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="classrooms", to="sbook.course"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="levels",
            field=models.ManyToManyField(
                blank=True, related_name="classrooms", to="sbook.level"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="series",
            field=models.ManyToManyField(
                blank=True, related_name="classrooms", to="sbook.serie"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[("t", "teacher"), ("s", "student")], max_length=2
            ),
        ),
        migrations.DeleteModel(
            name="SchoolUser",
        ),
    ]
