# Generated by Django 4.0.6 on 2024-05-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbook', '0002_user_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbookAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteAccount', to='sbook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('redactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='note.noteuser')),
            ],
        ),
    ]
