# Generated by Django 5.0.6 on 2024-06-11 18:08

import django.db.models.deletion
import mdeditor.fields
import profile_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0006_alter_note_description"),
        ("sbook", "0014_remove_serie_levels_course_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.RenameField(
            model_name="bookmark",
            old_name="user",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="note",
            name="starred",
        ),
        migrations.RemoveField(
            model_name="noteuser",
            name="starred",
        ),
        migrations.RemoveField(
            model_name="noteuser",
            name="stars",
        ),
        migrations.AddField(
            model_name="note",
            name="series",
            field=models.ManyToManyField(related_name="notes", to="sbook.serie"),
        ),
        migrations.AddField(
            model_name="noteuser",
            name="starred_notes",
            field=models.ManyToManyField(related_name="starred_by", to="note.note"),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="position",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="profile",
            field=models.ImageField(
                default=profile_images.get_random_file, upload_to="media/profiles"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="stars",
            field=models.IntegerField(default=0),
        ),
    ]
