# Generated by Django 5.0.6 on 2024-06-11 18:31

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0007_notecontent_rename_user_bookmark_author_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoteContent",
        ),
        migrations.AddField(
            model_name="note",
            name="content",
            field=mdeditor.fields.MDTextField(default="nothing just content"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
