# Generated by Django 5.0.6 on 2024-06-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0008_delete_notecontent_note_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="classrooms",
        ),
    ]
