# Generated by Django 5.0.6 on 2024-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0009_remove_note_classrooms"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="classrooms",
            field=models.ManyToManyField(related_name="notes", to="school.classroom"),
        ),
    ]
