# Generated by Django 5.0.6 on 2024-06-13 17:54

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0010_note_classrooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", mdeditor.fields.MDTextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_notes",
                        to="note.noteuser",
                    ),
                ),
            ],
        ),
    ]
