# Generated by Django 5.0.6 on 2024-06-15 16:41

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0011_shortnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortnote",
            name="description",
            field=mdeditor.fields.MDTextField(default=""),
        ),
        migrations.AddField(
            model_name="shortnote",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
