# Generated by Django 5.0.6 on 2024-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sbook", "0003_level_user_bio_user_profile_course_serie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("profile", models.ImageField(upload_to="")),
                ("description", models.CharField(max_length=255)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="classrooms", to="sbook.course"
                    ),
                ),
                (
                    "levels",
                    models.ManyToManyField(related_name="classrooms", to="sbook.level"),
                ),
            ],
        ),
    ]
