# Generated by Django 5.0.6 on 2024-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
        ("sbook", "0003_level_user_bio_user_profile_course_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="members",
            field=models.ManyToManyField(related_name="classrooms", to="sbook.user"),
        ),
    ]
