# Generated by Django 5.0.6 on 2024-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_classroom_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="description",
            field=models.TextField(),
        ),
    ]
