# Generated by Django 5.0.6 on 2024-06-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_classroom_series_alter_classroom_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
